### PR TITLE
solidity: Fix failing build

### LINKED ISSUE #2379: [Solidity] build failure cause unknown
Hello,

When I consult the build log, I see the following

```
Step #1: error pulling image configuration: Get https://storage.googleapis.com/artifacts.oss-fuzz-base.appspot.com/containers/images/sha256:ad499a28d661dcad45440d28ef96a0008e134cced40daf753c8cf3a41174aa6f?access_token=ya29.c.EmL_BnLGFnuFF0S91cPorIcwPhHa20UJXArLWP0iLycHop29oit2NjvPgbBsg3dx_BW9Y7LmjkfKHQsnHwe2jC3oPB96cdiE6EyBIr8Aa5AStL3m4xriJ5kvgLcIV3maJeGcoA: dial tcp 74.125.20.128:443: i/o timeout
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: exit status 1
```

Any idea why build is failing?

### PR DESCRIPTION
**Pull request by bshastry**
(closes #2379 )

Solidity has over 90k (minimized!) test inputs across 8 fuzzers with the highest seed corpus containing close to 25k files. The build was failing because we did this

```
$ zip -ujq <seed_corpus_dir.zip> seed_corpus_dir/* &> /dev/null
```

and bash wild card expansion complained that the argument list is too long. Moreover, it wasn't showing up in the logs because of the redirection of stdout/err to `/dev/null`.

The PR fixes this by doing

```
$ zip -rjq <seed_corpus_dir> seed_corpus_dir
```

### CODE REVIEW

File: projects/solidity/build.sh [hunk 1]
```diff
@@ -66,7 +66,7 @@ rm -f $OUT/*.zip
 for dir in $SRC/solidity-fuzzing-corpus/*;
 do
 	name=$(basename $dir)
-	zip -ujq $OUT/$name.zip $dir/* &>/dev/null
+	zip -rjq $OUT/$name $dir
```
Comment (Dor1s) [inline projects/solidity/build.sh]: Are you sure you need `-j`? We read the corpus directories recursively, so the flat structure is not necessary.
