### PR TITLE
[llvm] Add clang-proto-fuzzer.

### LINKED ISSUE #790: add clang-proto-fuzzer to oss-fuzz
I am trying to add clang-proto-fuzzer to oss-fuzz (as part of the `llvm` project). 
This is the diff: 
```
--- a/projects/llvm/build.sh
+++ b/projects/llvm/build.sh
@@ -32,8 +32,10 @@ cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../llvm \
     -DCMAKE_C_COMPILER=`pwd`/../build0/bin/clang \
     -DCMAKE_CXX_COMPILER=`pwd`/../build0/bin/clang++ \
     -DLLVM_USE_SANITIZE_COVERAGE=YES \
+    -DCLANG_ENABLE_PROTO_FUZZER=ON \
     -DLLVM_USE_SANITIZER=Address
 
-ninja clang-fuzzer
-
-cp bin/clang-fuzzer $OUT
+for fuzzer in clang-fuzzer clang-proto-fuzzer; do
+  ninja $fuzzer
+  cp bin/$fuzzer $OUT
+done

```

However, I get a build failure while configuring libprotobuf-mutator: 
```
[48/71] Linking CXX executable examples/libfuzzer/libfuzzer_example
FAILED: : && /src/build/../build0/bin/clang++   -fno-exceptions -Werror -Wall -O3 -DNDEBUG  -fsanitize-coverage=trace-pc-guard,trace-cmp examples/libfuzzer/CMakeFiles/libfuzzer_bin_example.dir/li
bfuzzer_bin_example.cc.o  -o examples/libfuzzer/libfuzzer_bin_example  examples/libfuzzer/libfuzzer-example-proto.a src/libfuzzer/libprotobuf-mutator-libfuzzer.a external.libfuzzer/src/external.l
ibfuzzer-build/libFuzzer.a src/libprotobuf-mutator.a /usr/local/lib/libprotobuf.so -pthread -Wl,-rpath,/usr/local/lib && :
examples/libfuzzer/libfuzzer-example-proto.a(libfuzzer_example.pb.cc.o): In function `libfuzzer_example::protobuf_libfuzzer_5fexample_2eproto::TableStruct::InitDefaultsImpl()':
libfuzzer_example.pb.cc:(.text+0x76): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
examples/libfuzzer/libfuzzer-example-proto.a(libfuzzer_example.pb.cc.o): In function `libfuzzer_example::protobuf_libfuzzer_5fexample_2eproto::AddDescriptorsImpl()':
libfuzzer_example.pb.cc:(.text+0x14d): undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_tra
its<char>, std::allocator<char> > const&))'
examples/libfuzzer/libfuzzer-example-proto.a(libfuzzer_example.pb.cc.o): In function `libfuzzer_example::Msg::Msg()':
libfuzzer_example.pb.cc:(.text+0x290): undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'

```

Do we need to build `libfuzzer_example ` when building libprotobuf-mutator here? 

If yes, can we honor the CFLAGS provided by OSS-Fuzz? 
Looks like this build crashes because OSS-Fuzz wants libc++ instead of libstdc++.

### PR DESCRIPTION
**Pull request by morehouse**
- Move protobuf build to build.sh to avoid container overflow false positive
- Build all fuzzers using OSS-Fuzz environment variables.
- Eliminate ToT clang build.

Building protobuf in build.sh allows us to build it with ASan and avoid container overflow false positives.  And if we ever want to use MSan, we will probably have to build in build.sh anyways.  However, it appears this prevents using UBSan due to undefined behavior in protobuf.

Also, we'll need further changes in LLVM (and protobuf-mutator?) to get MSan working with clang-proto-fuzzer since clang-proto-fuzzer links with protobuf-mutator which in turn links with other things.

Closes #790.

### CODE REVIEW

File: projects/llvm/build.sh [hunk 1]
```diff
@@ -22,6 +22,40 @@
 # and LLVM's own copy of libFuzzer.
 # TODO(kcc): honor CFLAGS/CXXFLAGS to allow building with msan/ubsan
 
+# Build and install protobuf
+pushd protobuf-3.3.0
```
Comment (kcc) [inline projects/llvm/build.sh]: use a shell function, call it inside ()

File: projects/llvm/build.sh [hunk 2]
```diff
@@ -34,7 +68,7 @@ cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../llvm \
     -DLLVM_USE_SANITIZE_COVERAGE=YES \
     -DLLVM_USE_SANITIZER=Address
 
-for fuzzer in clang-fuzzer clang-format-fuzzer llvm-dwarfdump-fuzzer; do
+for fuzzer in clang-format-fuzzer llvm-dwarfdump-fuzzer; do
```
Comment (kcc) [inline projects/llvm/build.sh]: please migrate the remaining targets upstream and delete the last part from here

**Comment by kcc** [comment]
Cool!
