### PR TITLE
Fix for rust and swift coverages

### LINKED ISSUE #6268: Support for LLVM 13 fuzzing
I got a notification that the flate2 project's coverage build [is failing](https://oss-fuzz-build-logs.storage.googleapis.com/log-1ef4e2ba-e147-44f4-978b-3245ec2c068e.txt) and has the error message:

```
Step #5: warning: /workspace/out/coverage/dumps/fuzz_gz_roundtrip.16218861006045500770_0.profraw: Unsupported instrumentation profile format version
Step #5: error: No profiles could be merged.
```

AFAIK nothing about flate2 itself has changed, but the most recent change I can think of is that the Rust compiler upgraded to LLVM 13 over the weekend. I suspect that the new LLVM version may have updated something about coverage instrumentation?

### PR DESCRIPTION
**Pull request by catenacyber**
Fixes #6268

Replaces #6449 

Introduces lvm-cov-rel, a tool to convert profraw files from version 5 and 7/clang-13 to version 7/clang-14

cc @jonathanmetzman @inferno-chromium 
Tested with
```
python3 infra/helper.py build_image --no-pull base-builder
python3 infra/helper.py build_image --no-pull base-builder-rust
python3 infra/helper.py build_image --no-pull base-runner
export PROJECT=suricata
python3 infra/helper.py build_image --no-pull $PROJECT
python3 infra/helper.py build_fuzzers --sanitizer coverage $PROJECT
python3 infra/helper.py coverage --no-corpus-download $PROJECT
```

with projects suricata, image-rs and swift-nio

### CODE REVIEW

File: infra/base-images/base-runner/coverage [hunk 1]
```diff
@@ -99,7 +99,12 @@ function run_fuzz_target {
     return 0
   fi
 
-  llvm-profdata merge -j=1 -sparse $profraw_file_mask -o $profdata_file
+  llvm-profdata merge -j=1 -sparse $profraw_file_mask -o $profdata_file || (
+    # on error, try to first run llvm-cov-rel to fix profraw file
```
Comment (jonathanmetzman) [inline infra/base-images/base-runner/coverage:103]: This is pretty hacky to me. Why can't you just do the latter when using rust or swift?
Or would doing the latter for every language work.

File: infra/base-images/base-builder/cargo [hunk 2]
```diff
@@ -35,7 +35,11 @@ then
     # go into fuzz directory if not already the case
     cd fuzz || true
     fuzz_src_abspath=`pwd`
-    export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix fuzz_targets=$fuzz_src_abspath/fuzz_targets"
+    # default directory is fuzz_targets, but some projects like image-rs use fuzzers
```
Comment (jonathanmetzman) [inline infra/base-images/base-builder/cargo:38]: Please begin with capital and end with period.

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go [hunk 3]
```diff
@@ -0,0 +1,180 @@
+package main
```
Comment (jonathanmetzman) [inline infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:1]: In the future I would prefer code for OSS-Fuzz be written in python.
I still need to figure out how to remove the go toolchain from the runner image because we didn't stick to this policy. All of the other code in OSS-Fuzz is python or bash (also an unfortunate choice), lets try to do python only from now on.

File: infra/base-images/base-builder/cargo [hunk 4]
```diff
@@ -35,7 +35,11 @@ then
...
+    while read i; do
+        export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix $i=$fuzz_src_abspath/$i"
+        # bash while syntax so that we modify RUSTFLAGS in main shell instead of a subshell
```
Comment (jonathanmetzman) [inline infra/base-images/base-builder/cargo:41]: Please begin with capital and end with period.

File: infra/base-images/base-runner/coverage (hunk 1 above)
Comment (jonathanmetzman) [reply infra/base-images/base-runner/coverage:103]: Please begin with capital and end with period.

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go [hunk 5]
```diff
@@ -0,0 +1,180 @@
...
+		d.FunctionPointer = binary.LittleEndian.Uint64(data[offset+24 : offset+32])
+		d.Values = binary.LittleEndian.Uint64(data[offset+32 : offset+40])
+		d.NumCounters = binary.LittleEndian.Uint32(data[offset+40 : offset+44])
+		d.NumValueSites = make([]uint16, h.ValueKindLast+1)
+		for j := 0; j <= int(h.ValueKindLast); j++ {
+			d.NumValueSites[j] = binary.LittleEndian.Uint16(data[offset+44+2*j : offset+46+2*j])
+		}
+
+		relativizeAddress(data, offset+16, dataref, sectPrfCnts, sectPrfData)
+		// cf CountersDelta -= sizeof(*SrcData); in __llvm_profile_merge_from_buffer
```
Comment (jonathanmetzman) [inline infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:131]: Why not delete this?

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+}
+
+func main() {
+	flag.Parse()
+
+	if len(flag.Args()) != 3 {
+		log.Fatalf("needs exactly three arguments : binary, profraw, output")
+	}
+
+	// first find llvm profile sections addresses in the elf
```
Comment (jonathanmetzman) [inline infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:146]: Please begin with capital and end with period.

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go [hunk 7]
```diff
@@ -0,0 +1,180 @@
...
+		log.Fatalf("failed to read elf: %v", err)
+	}
+	sectPrfCnts := uint64(0)
+	sectPrfData := uint64(0)
+	for i := range f.Sections {
+		if f.Sections[i].Name == "__llvm_prf_cnts" {
+			sectPrfCnts = f.Sections[i].Addr
+		} else if f.Sections[i].Name == "__llvm_prf_data" {
+			sectPrfData = f.Sections[i].Addr
+			// maybe rather sectPrfCntsEnd as f.Sections[i].Addr + f.Sections[i].Size for __llvm_prf_cnts
```
Comment (jonathanmetzman) [inline infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:158]: Please begin with capital and end with period.

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go [hunk 8]
```diff
@@ -0,0 +1,180 @@
...
+		}
+	}
+	if sectPrfCnts == 0 || sectPrfData == 0 {
+		log.Fatalf("Elf has not __llvm_prf_cnts and __llvm_prf_data sections")
+	}
+
+	// process profraw file
```
Comment (jonathanmetzman) [inline infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:165]: Please begin with capital and end with period.

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go [hunk 9]
```diff
@@ -0,0 +1,180 @@
...
+	data, err := ioutil.ReadFile(flag.Args()[1])
+	if err != nil {
+		log.Fatalf("failed to read file: %v", err)
+	}
+	err, data = relativizeProfraw(data, sectPrfCnts, sectPrfData)
+	if err != nil {
+		log.Fatalf("failed to process file: %v", err)
+	}
+
+	// write output file
```
Comment (jonathanmetzman) [inline infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:175]: Please begin with capital and end with period.

**Review by jonathanmetzman — COMMENTED** [review]
Thanks for this. This is better than #6449 but I think could still be improved.

File: infra/base-images/base-runner/coverage (hunk 1 above)
Comment (catenacyber) [reply infra/base-images/base-runner/coverage:103]: Yes, or we can do it in every case, as it leaves clang-14 profraw files identical

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 3 above)
Comment (catenacyber) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:1]: So, do you want me to rewrite this in python ?

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 5 above)
Comment (catenacyber) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:131]: This comment explains the addition afterwards

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 3 above)
Comment (jonathanmetzman) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:1]: Not necessary for this PR, but in future, I'd prefer it if we had as little go code as possible yes.

File: infra/base-images/base-builder/cargo (hunk 2 above)
Comment (catenacyber) [reply infra/base-images/base-builder/cargo:38]: ok, done

File: infra/base-images/base-builder/cargo (hunk 4 above)
Comment (catenacyber) [reply infra/base-images/base-builder/cargo:41]: done

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 6 above)
Comment (catenacyber) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:146]: ok

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 7 above)
Comment (catenacyber) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:158]: ok

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 8 above)
Comment (catenacyber) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:165]: ok

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 9 above)
Comment (catenacyber) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:175]: ok

**Comment by catenacyber** [comment]
@jonathanmetzman I pushed a new version with the right syntax for comments

File: infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go (hunk 3 above)
Comment (jonathanmetzman) [reply infra/base-images/base-runner/gocoverage/llvm-cov-rel/llvm-profraw-relative.go:1]: This PR LGTM, but if it won't take to long, could you please convert this script to Python?
Thanks!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by catenacyber** [comment]
Looks like base-runner dit not get updated yet so today's coverage builds still fail

I will wait to see how it goes before trying python

**Comment by catenacyber** [comment]
Still no updated version of base-runner ...
Is something going wrong ?

**Comment by catenacyber** [comment]
ping @jonathanmetzman why do the docker images not updated ?
When I run `python infra/helper.py pull_images` I always get 
```
latest: Pulling from oss-fuzz-base/base-runner
Digest: sha256:41c2805f5f035993f7582796ed954b7acd9c14873a9d73860cd542cdeba1c1c6
```

**Comment by catenacyber** [comment]
Getting some fixes :-)
All swift projects, and C++ projects with rust are ok

But none of the pure rust projects are working yet... because of a new change in LLVM 14 cf #6551
