### PR TITLE
Fix build coverage of libprotobuf-mutator

### LINKED ISSUE #597: libprofobuf-mutator build failure
https://oss-fuzz-build-logs.storage.googleapis.com/log-1549301b-f0aa-4979-b656-4d9d62f0679d.txt

@vitalybuka - can you please take a look.

### PR DESCRIPTION
**Pull request by vitalybuka**
Fixes #597

### CODE REVIEW

File: projects/libprotobuf-mutator/build.sh [hunk 1]
```diff
@@ -21,10 +21,13 @@ cp -f $SRC/*.dict $SRC/*.options $OUT/
 mkdir -p build
 pushd build
 rm -rf *
-cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release \
+
+CXXFLAGS="$CXXFLAGS -Wl,-lpthread -Wno-unused-command-line-argument" \
```
Comment (kcc) [inline projects/libprotobuf-mutator/build.sh]: Why this? 
Did you understand why we had this warning?

Comment (vitalybuka) [inline projects/libprotobuf-mutator/build.sh]: Please check #604

Comment (vitalybuka) [inline projects/libprotobuf-mutator/build.sh]: pthread is needed by probuf library if --stdlib=libc++ specified.
Compiler does add -pthread and looks like it's expected behavior as libc++ user may use no threads  related std:: stuff.
As it's only libprotobuf-mutator issue, and no other oss projects need this, I added -pthread into cmake file there.
